### ISSUE TITLE
is it possible to include html content?

### ISSUE THREAD

**Issue by laurencefass** [tjrexer/react-notifications#34] opened 2021-02-18 18:12 UTC
Is it possible to add title or content as HTML? To add clickable links, formatting, images etc. Do you have any plans to include this in the future?

thanks

**Comment by tjrexer** [comment] 2021-12-11 18:39
Duplicate of #6.  I would like to be able to, just don't have enough time right now.

**Closed as completed by tjrexer** 2021-12-11 18:39 UTC
Labels: duplicate
